spring:
  datasource:
    url: jdbc:h2:file:./db/prod/shelob-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.H2Dialect
